#!/bin/bash

current_pwd=$(pwd)

if [ ! $1X = nolibsX ]; then
    cd libs && ./buildit
fi


PROJ="ais_filter ais_server"

#for f in ${PROJ}; do
#    cd ${current_pwd} 
#    echo "generating ${f}"
#    ./mmsdk.lua src/${f}/${f}_config_api.lua
#done
