#!/bin/bash


OUTDIR=./bin
#PROJ="ais_filter ais_server" 
PROJ="ais_filter"

LIBUV_A=$(find ./libs -name libuv.a)
LIBLUA_A=$(find ./libs -name liblua.a)
LIBCONFIG_A=$(find ./libs -name libconfig.a)

LIBCONFIG_DIR=$(dirname $(find -name libconfig.h))

# ensure output is available
if [ ! -d ${OUTDIR} ]; then mkdir ./bin; fi 

for f in ${PROJ}; do
  gcc -O3 -DNDEBUG -o ${OUTDIR}/${f} -I${LIBCONFIG_DIR} -Isrc/lib -Ilibs/lua-5.2.2/src -Ilibs/libuv/include \
  $(ls src/lib/*.c src/${f}/*.c) \
  ${LIBUV_A} ${LIBCONFIG_A} -lpthread -lrt -lm
  strip -s ${OUTDIR}/${f}
done

#CC flags
MMCC="-fwhole-program -ffast-math -msse2"

#ais decoder (full decode)
f=ais_decoder
gcc -DSAD_ENABLE_ALL -O3 -DNDEBUG -o ${OUTDIR}/${f} -Isrc/lib src/${f}.c  src/lib/sad.c src/lib/sub0.c
strip -s ${OUTDIR}/${f}
