#!/bin/bash
#
# chkconfig: 2345 85 15
# description: Starts and stops ais_filter

# Source function library.
if [ -f /etc/rc.d/functions ];
then
    . /etc/init.d/functions
fi

MEXE=/usr/local/bin/ais_filter
MCONF_DIR=/etc/ais_filter
MLOG=/var/log/ais_filter.log

sanity()
{
        [ -f ${MEXE} ] || echo "[ ERR] missing ${MEXE}"
        [ -d ${MCONF_DIR} ] || echo "[ ERR] missing ${MCONF_DIR}"
}

status()
{
        sanity
        netstat -plunt | grep $(basename ${MEXE})      
}


start()
{
        sanity
        for f in $(ls -1 ${MCONF_DIR}/*.conf); do
            echo "[INFO] starting ${MEXEC} $f"
            ${MEXE} ${f} &
        done
}

stop()
{
        killall $(basename ${MEXE}) -9
        
}

restart()
{
        stop
        sleep 2
        start
}

# See how we were called.
case "$1" in
  status)
        status
        ;;
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo $"Usage: service aisf {start|stop|restart|status}"
        exit 1
esac

