#!/bin/bash

LIBUV_ID=libuv_131201
LIBLUA_ID=lua-5.2.2
LIBCONFIG_ID=libconfig-1.4.9

ROOT_PWD=$(pwd)


#liblua
cd ${ROOT_PWD}
if [ -d ${LIBLUA_ID} ]; then rm -rf ${LIBLUA_ID};fi
tar xvfz ${LIBLUA_ID}.tgz
cd ${LIBLUA_ID}
make linux 


#libuv
cd ${ROOT_PWD}
if [ ! -d ${LIBUV_ID} ]; then rm -rf ${LIBUV_ID};fi
tar xvfz ${LIBUV_ID}.tgz
cd libuv

if [ $1 ]; then
  if [ ${1}X==winX ]; then
     make -f Makefile.mingw
  fi
else
  which gyp || echo "install gyp"
  ./gyp_uv.py -f make && make -C out
  
fi

#libconfig
cd ${ROOT_PWD}
tar xvfz libconfig-1.4.9.tar.gz 
cd ${LIBCONFIG_ID}
./configure && make

